Some mappings
valoeghese/FCMappings pull request #1
Opened 2019-12-21 02:21 UTC by ramidzkh

Is it me or do 40% of the classes relate to collections?

2019-12-21 02:24 UTC, Chocohead commented on mappings/fastcraft/compat/EnumForeignMods.mapping
> +	METHOD values values ()[Lfastcraft/k;
Probably don't need this line

2019-12-23 00:56 UTC, valoeghese requested changes

2019-12-23 00:56 UTC, valoeghese commented on mappings/fastcraft/FastcraftClassTransformer.mapping
> +CLASS fastcraft/J fastcraft/FastcraftClassTransformer
`fastcraft/asm` package

2019-12-23 00:56 UTC, valoeghese commented on mappings/fastcraft/FastcraftFMLTweaker.mapping
> +CLASS fastcraft/Tweaker fastcraft/FastcraftFMLTweaker
isn't this already deobf?

2019-12-23 00:56 UTC, valoeghese commented on mappings/fastcraft/MapHolder.mapping
> +CLASS fastcraft/aZ fastcraft/MapHolder
`fastcraft/util` package probably

2019-12-23 00:56 UTC, valoeghese commented on mappings/fastcraft/ResizeUnicodeTextFontRenderer.mapping
> +CLASS fastcraft/U fastcraft/ResizeUnicodeTextFontRenderer
subpackage?

2019-12-23 00:56 UTC, valoeghese commented on mappings/fastcraft/TextureAtlasSpriteComparator.mapping
> +CLASS fastcraft/aa fastcraft/TextureAtlasSpriteComparator
subpackage?

2019-12-23 00:56 UTC, valoeghese commented on mappings/fastcraft/TransformerHook.mapping
> +CLASS fastcraft/L fastcraft/TransformerHook
`fastcraft/asm` package probably

2019-12-23 00:56 UTC, valoeghese commented on mappings/fastcraft/ZipEntryInputStream.mapping
> +CLASS fastcraft/aE fastcraft/ZipEntryInputStream
`fastcraft/util` package

2020-02-05 21:20 UTC, valoeghese commented
Hi resolve errors thank

2020-04-26 04:36 UTC, ramidzkh commented
wtf is this

2020-12-08 08:22 UTC, valoeghese commented
whatever I'll merge it

2020-12-08 08:22 UTC, merged